import { createApp } from 'vue';
import '@/assets/style/common.less';
import App from './App.vue';
import router from './router';
import store from './store';
import addAntd from '@/plugins/antd';
// import { contextmenu } from './utils/menu';
// import DB from '@/plugins/datastore';
// contextmenu();
const app = createApp(App);
addAntd(app);
// app.config.globalProperties.$db = DB;
app.use(store).use(router).mount('#app');
export default app;